### ISSUE TITLE
Ensure that all public APIs are documented

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#86]

**Comment by ramya-rao-a** [comment]
As part of reviewing the docs for Preview 1, I have reviewed the API set as well, below are my notes
on some changes that I am proposing we look at:



- **`maxConcurrentCalls` in the streaming receiver & `maxConcurrentCallsPerSession` in the session streaming receiver are options exposed to the user, but dont work as documented**
    - Since we are not sure how this is supposed to work, there are no tests to cover this feature. 
    - We can keep the default values for now and not expose this option to the user.
    - Once we understand the feature and there is user ask for the same, we can expose this to the users.

- **Promise returned by Send and SendBatch shouldn't resolve to any object**
    - These promises currently resolve to a `Delivery` object which is an internal implementation of the object that was sent. The user has no use for it and so should not be returned.

-  **listMessageSessions has skip as the first parameter making it mandatory**
   -  Remove the skip parameter. It can be added as an optional parameter later if there is user feedback.
   - The only reason this exists is because the underlying api allows you to skip. .Net SDK hasnt implemented this feature, so its not like there has been existing user feedback to have this feature.

- **SessionManager**
  - We don't have tests for the various options the session manager takes as input.
  - Python has a simple sample for this and doesnt have this as a built-in feature. 
  - I would suggest to pull back on this and not ship this in Preview 1. If we can simplify this and share it as a sample instead of a feature, then that would be 1 less complicated feature to support. 
  - Else, understand all its options, have test cases and then ship.

- **acceptSession()**
   - The name acceptSession() is not intuitive to receive an object that is then used to receive messages from sessions. Suggested name: `getSessionClient` 

- **Input options to acceptSession(), session streaming receiver and session manager**
   - Clean up needed. There is all kinds of overlap resulting in user getting exposed to options that they dont need
   - Streaming Receiver takes in parameter `maxConcurrentSessions` & `maxMessageWaitTimeoutInSeconds` which only makes sense when it is called from Session Manager and not when called by user
   -  Streaming Receiver takes in `receiveMode` which is redundant as the same is passed to `acceptSesion()`
   - `acceptSession()` takes in `autoComplete` and `maxAutoRenewDurationInSeconds` which it has no need for. Both are needed for streaming receiver and Session Manager.

- **Options that have the words "inSeconds"**
   - **Sugggestion**: Strip the word "inSeconds", ensure documentation captures the fact that it is in seconds. Ensure we deal with seconds in all user facing APIs
   - The name of these options are not self-explainatory. Removing "inSeconds" gives us some extra letters to have more meaningful names.

- **ReceiveBatch: Consider removing the third parameter**
    - This third parameter is the time for which we would wait for a new message after receiving the current message
    - The second parameter is for total time to wait to get the n messages asked for.
    - The third parameter is complicating what would be a simple api.
    - .Net SDK doesnt hav this feature, meaning there was no strong user ask for the same.
    - If we do get user feedback about this, then we can always add it back


This one we might want to take up for Preview 2

- **The handler returned by `receive()` function whose sole purpose is to stop receiving messages** 
    - **Sugggestion**: Dont return any handler. 
    - None of the other SDKs have this model of using a handler to stop receiving messages. Instead, the 
       receiver client is expected to be closed by the user when they want to stop receiving messages
    - Our streaming receiver for sessions doesnt have return such a handler either. The messageSession is expected to be closed by the user when they want to stop receiving messages
    - Having a timeout instead of the "stop" behavior would be much simpler

**Comment by ramya-rao-a** [comment]
https://github.com/Azure/azure-sdk-for-js/pull/992 has all changes outlined above except the last 3 points on 
- InSeconds in the name
- receiveBatch losing the third parameter
- receive not returning the handler

**Comment by ramya-rao-a** [comment]
Recent Notes:

**Function Signatures**

- The 3rd parameter to `receiveBatch()` can be skipped. This was introduced to avoid waiting too long for messages when the queue might not have the amount asked for. While the feature is needed, it doesn't need to be customized by the user
- Introduce timeout for the `receive()` call which provides the streaming behavior. This avoids the need to have the `receiveHandler` that is returned today whose sole purpose was to stop the streaming receiver. This would be optional. When no timeout is provided, the receiver runs until `close()` is called on the receiver.
- Remove all inconsistencies between the streaming receiver for session and non session scenarios

**MessageSession vs SessionClient vs SessionReceiver**

The way users receive messages from a session enabled queue is drastically different from the normal scenario for the main reason that we need to support the case when user asks for messages without knowing the session-id.

Due to this, we now have the `MessageSession` object being returned to the user. This has the receiver for the session that the user asked for or a random session if the user doesn't provide a session id.

It is not very intuitive as to what a `MessageSession` does, so we previously renamed it to `SessionClient` as it has the receive related features just like a QueueClient or a SubscriptionClient. But "client" corresponds to a Service Bus entity i.e a queue, topic or a subscription. The `MessageSession` is essentially a receiver not a client. Therefore, the below proposal

_QueueClient_
  - `getSender()`:  Gets a sender which can then be used for send, sendBatch, schedule & cancel scheduled messages
  - `getReceiver()`: Gets a receiver which can then be used for receive, receiveBatch, receiveDeferred, renewLock
  - `getSessionReceiver()`: Gets a session receiver does all of the above, plus getState(), setState()
  - Other functions like `peek()`, `peekFromSequenceNumber()` and `close()` stay as is

_TopicClient_
  - `getSender()`:  Gets a sender which can then be used for send, sendBatch, schedule & cancel scheduled messages
  - `close()`

_SubscriptionClient_
  - `getReceiver()`: Gets a receiver which can then be used for receive, receiveBatch, receiveDeferred, renewLock
  - `getSessionReceiver()`: Gets a session receiver does all of the above, plus getState(), setState()
  - Other functions like `peek()`, `peekFromSequenceNumber()` and `close()` stay as is

**Comment by ramya-rao-a** [comment]
Advantages of having the sender/receiver separate from the queue client

- User can create multiple receivers without having to create new queue/subscription clients. Which logically makes more sense in the new model.
- It is much more clear that one would need a different kind of a receiver when using sessions.
- Points of failure when using normal receive features on a session enabled entity reduces from 4 to 1.

**Comment by ShivangiReja** [comment]
These suggestions look much more cleaner that way.

I would like to suggest that as we will use only one parameter for receiveBatch, so we can change the parameter name like operationTimeout.

**Comment by HarshaNalluru** [comment]
- I agree that the name `SessionReceiver` makes more sense.

"Remove all inconsistencies between the streaming receiver for session and non session scenarios"
- This clears a lot of confusion


receive() call 
   - Timeout is a much needed thing, glad that you added.
   - Can we also add an optional parameter "maximum number of messages to be received" to the receive() call ?

@ramya-rao-a

**Comment by HarshaNalluru** [comment]
@ShivangiReja 
> Since we are using getSender() method, we can pass one optional parameter sessionId for session enabled queues/subscription.

How does this help ? or How are we going to use the sessionId while sending ?

**Comment by ShivangiReja** [comment]
@HarshaNalluru  check the updated comment.

**Comment by ramya-rao-a** [comment]
Thanks for the feedback @ShivangiReja and @HarshaNalluru!

**Adding `sessionId` as a parameter to getSender()**

Unlike receivers, the same sender link can be used to send data to different sessions.

My one concern with passing `sessionId` to `getSender()` would be that if the user wanted to send to different sessions, they would now have to either create a new sender or set the sessionId in each message and we can use that to override the sessionId passed to getSender().
In both cases, the ability to pass the sessionId to `getSender()` doesnt benefit the user much.

But I want to keep this possibility open. If we have some user feedback on the same lines, we should definitely revisit this idea.

**Adding `sessionId` as a parameter to getReceiver()**

This is definitely something we should do, but since the underlying changes are not trivial, I didnt pick it up for Preview 1. But, we can pick this up for Preview 2

Some things that make this change non-trivial
- `SessionReceiver` uses the same underlying receiver link for both streaming and batching features. But for non sessions, we have 2 separate classes using 2 different receiver links
- Creating a `SessionReciever` today is a async process where as `getReceiver()` is not async. So we cant combine them without a lot of changes. The `SessionReceiver` is async because it actually creates the underlying receiver link. But for non sessions, the underlying receiver links are lazily created i.e `getReceiver()` doesnt create the underlying receiver links, calling `receive()` or `receiveBatch()` creates them.

**Changing maxWaitTimeinSeconds to operationTimeout**

Yes, definitely. I was thinking of a separate PR to do renaming of all time related parameters as we still haven settled down on whether we want "seconds" in the name or not

**Add optional param "maximum number of messages to be received" for receive**

That's a very good idea! I'll create an issue for that and we can take it for Preview 2. There are 2 reasons to do this in Preview 2 instead of Preview 1
- Doing this in Preview 2 will not break any function signature since the new param will just be an addition to the existing `options` parameter and it will be optional
- This would a whole new feature, we dont have anything like this in either of .Net, Go or Python SDK. So no pressure to have it in the first round.

**Comment by ramya-rao-a** [comment]
@ShivangiReja, @HarshaNalluru 

Logged https://github.com/Azure/azure-sdk-for-js/issues/1012 and https://github.com/Azure/azure-sdk-for-js/issues/1011 to track the work meant for Preview 2

**Comment by ramya-rao-a** [comment]
Final update here is that of https://github.com/Azure/azure-sdk-for-js/issues/1011

**Comment by ramya-rao-a** [comment]
Final look of our apis for Preview 1

![image](https://user-images.githubusercontent.com/16890566/52140289-38bc4580-2607-11e9-8916-218e2fa4458e.png)

![image](https://user-images.githubusercontent.com/16890566/52140307-44a80780-2607-11e9-9a4d-9936d2de28ad.png)

![image](https://user-images.githubusercontent.com/16890566/52140324-57224100-2607-11e9-91d2-7cb5a273cc85.png)
