### ISSUE TITLE
Issue receiving more than 2047 messages

### ISSUE THREAD

**Issue by gcstarr** [Azure/azure-service-bus-node#89]
**Describe the bug**
When using the queueClient and calling batchReceive(), I cannot receive more than 2047 messages in total, over multiple receiveBatch calls, or a single call, unless I close the client and instantiate a new one every time I hit 2047.

**To Reproduce**
This can be reproduced by a single batchReceive() call with maxMessageCount > 2047, or by making several repeated batchReceive() calls with a smaller maxMessageCount that adds up to >2047 over several calls. Of course the queue must have a sufficient number of messages in it. 

**Expected behavior**
I am not limited over multiple calls to a grand total of 2047.

**Package-version**: Commit 99b6bff
**node.js version**: 10.14.1
**OS name and version**: Ubuntu 18.10

**Comment by amarzavery** [comment]
- Are you instantiating the queue client in receiveAndDelete mode or peekLock mode (default)?
  - If it is the peekLock mode (which is the default) then are you settling the messages (i.e. message.complete()/abandon()/defer()/deadLetter()) ?
  - the underlying amqp library (rhea) has a circular buffer with a hard limit set to 2048 (which is a reasonable limit). If you settle those messages then rhea will have more space in the circular buffer and will fetch more messages.
  - If you are receiving messages in the `receiveAndDelete` mode then as soon as the message is fetched from the queue, it is deleted from the service side. There is no need to ack. In that scenario you should be able to fetch more than 2047 messages. However, I am not sure if receiveAndDelete would be the best fit for you since it has the potential to lose messages.
- Btw, can you share your code snippet as that will provide insights into which mode you are setting while instantiating the client and what do you do with the list of received messages from receiveBatch()?

**Comment by gcstarr** [comment]
@amarzavery This is also an issue with the streaming receiver. If you run the receiveComplete example with enough messages (i.e. >2047) in the queue no messages are received after #2047. Here's the one I ran, just logging a counter instead of the message body, and upping maxConcurrentCalls to greatly speed up the process (though it will _eventually_ happen with the default maxConcurrentCalls):

[receiveComplete.zip](https://github.com/Azure/azure-service-bus-node/files/2696932/receiveComplete.zip)

**Comment by gcstarr** [comment]
I made the changes reflected in pull request #116, and they appear to resolve the issue for me.

**Comment by amarzavery** [comment]
@gcstarr -

Just trying to get a clear picture about the fix:

Whether you are receiving via `receiveBatch()` or via `receive()`:
 - if the `receiveMode` is `peekLock` then
    - while setting the message, one needs to set the delivery settled status to true. This will indicate rhea to remove the messages from the circular buffer.
- if the `receiveMode` is `receiveAndDelete` then rhea settles the delivery for us automatically and we need not do anything. Hence we do not see a problem of receiving more than 2047 messages.

Is the above understanding correct? If yes, then 
- Do we still need to drain the receiver? Would settling the deliveries be enough to resolve this issue?
- Or do we need to both?

**Comment by gcstarr** [comment]
* Your understanding matches mine.
  * You can see here (https://github.com/amqp/rhea/blob/master/lib/session.js#L331) that Rhea's `accept()` method (line 335) sends `undefined` to `update()`, which results in it checking the receive mode on line 331.
  * PeekLock mode is `1`, so `settled` is set to `false`.
  * This adheres to the AMQP standard (http://docs.oasis-open.org/amqp/core/v1.0/csprd01/amqp-core-transport-v1.0-csprd01.html#type-receiver-settle-mode, the description for `second`) that in that mode the receiver should only "settle" the delivery when the sender sends the appropriate disposition that it has been settled on its side. Thus, we need to update the delivery to `settled` when we get the `onSettled` event.

* We only need to drain the link_credit if a batch times-out without having received a full batch. Otherwise the remaining credits will still be there when we add another full-batch worth of credits for the next batchReceive() (a "credit leak"), eventually causing more link_credit than the circular buffer size, causing Rhea to emit a circular buffer overflow error if enough messages come in.
  * My other pull request (#107) should address this issue.

* Like most of you I'm off until the new year, so we can pick this back up then. Happy holidays!

**Comment by ramya-rao-a** [comment]
@gcstarr Thanks for all that information!

I wonder if the fix for this issue should be in the rhea library.

From the sdk's perspective, a request was sent to settle the message. When the message is settled, the `settled` event is fired. 
I would expect the `rhea` library to run `delivery.update(true)` before firing the `settled` event instead of us doing the same when listening to the `settled` event.

Thoughts?

**Comment by gcstarr** [comment]
Agreed that this makes sense for Rhea to handle for us. I would think most consumers would just want to call accept() and have the protocol-level-library (Rhea) handle updating its own buffer.

**Comment by ramya-rao-a** [comment]
@gcstarr This should be fixed with #151

If you are running the sdk from sources, run `npm install` after getting the latest from master to ensure you get the updated `rhea`.

We will release an update after #107 is merged.

**Comment by ramya-rao-a** [comment]
@gcstarr Please see https://github.com/Azure/azure-service-bus-node/issues/81#issuecomment-460897972
